articles/urls.py
from django.urls import path
# 같은 폴더 내에 있는 views를 불러올게요
from . import views

app_name = 'articles'

urlpatterns = [
    # '': articles/ 에 해당하는 정보만 받겠다
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),

    # input 넣을 수 있는 빈 도화지 페이지 만들기
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update', views.update, name='update'),
]
 

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # articles(앱이름) 폴더 내에 있는 urls.py로 가렴.
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.

# Model이라는 클래스를 상속받아옴
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

# 전체 게시물을 가져오는 코드
def index(request):
    # Article이라는 클래스에서 객체 전체를 가져올게
    articles = Article.objects.all()

    context = {
        'articles': articles
    }
    return render(request, 'index.html', context)


def detail(request, id):
    # 단일게시물이므로 article 단수형
    article = Article.objects.get(id=id)

    context = {
        'article': article,
    }
    
    return render(request, 'detail.html', context)


def new(request):
    return render(request, 'new.html')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article()
    article.title = title
    article.content = content
    article.save()

    # 제출 후 인덱스로
    # return redirect('articles:index')

    # 제출 후 디테일로
    return redirect('articles:detail', id=article.id)


def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()

    return redirect('articles:index')


# 기존 정보 보여줌
def edit(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article': article
    }

    return render(request, 'edit.html', context)


def update(request, id):
    # 새로운 정보
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 기존 정보
    article = Article.objects.get(id=id)

    article.title = title
    article.content = content
    article.save()

    return redirect('articles:detail', id=article.id)

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="card mt-4">
        <div class="card-header">
            {{ article.title }}
        </div>
        <div class="card-body">
            {{ article.content }}
        </div>
        <div class="card-footer">
            <p>{{ article.created_at }}</p>
            <a href="{% url 'articles:edit' id=article.id %}" class="btn btn-warning">Edit</a>
            <a href="{% url 'articles:delete' id=article.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
{% endblock %}

articles/templates/edit.html
<!-- new.html과 매우 비슷해서 복붙 후 수정 -->
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:update' id=article.id %}" class="mt-4" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{article.title}}">
        </div>

        <div class="mb-3">
            <label for="content" class="form-label">content</label>
            <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{article.content}}</textarea>
        </div>

        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Link</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td>{{article.id}}</td>
                <td>{{article.title}}</td>
                <td>
                    <!-- 중괄호퍼센트: 장고 문법 쓸거야 / url: '앱네임:url path의 name인자' -->
                    <a href="{% url 'articles:detail' id=article.id %}">detail</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

articles/templates/new.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:create' %}" class="mt-4" method="POST">
        <!-- 이 빈 도화지에 우리꺼라는 도장 찍는 것. post를 위해 빈 종이에 인증해두는 것. -->
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>
        </div>

        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

templates/base.html
<!-- 모든 페이지에 공통적으로 띄울 베이스 요소들 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" href="{% url 'articles:new' %}">New</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
          </div>
        </div>
    </nav>

    <!-- container: 바깥 테두리 영역에 여백 생성 -->
    <div class="container">
        <!-- 여기서 block은 꼭 쓰는 명령어, body는 그냥 바꿔도 됨. 다만 이후 파일들에서도 통일해줘야. -->
        {% block body %}
        
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>